apiVersion: v1
kind: Pod
metadata:
 name: guy
spec:
 containers:
 - name: app1
   image: supergiantkir/animals:bear
   ports:
   - containerPort: 80
   volumeMounts:
    - name: redis-persistent-storage
      mountPath: /data/redis

 - name: app2
   image: yanivomc/spring-music:latest
   ports:
   - containerPort: 8080
   volumeMounts:
    - name: redis-persistent-storage
      mountPath: /data/redis
 volumes:
  - name: redis-persistent-storage
    emptyDir: {} 